name: release
on:
  release:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  release:
    name: "Create new release"
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest, macos-15-intel]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Publish
        run: |
          npm ci
          npm run publish